bk-changeset-1.1353 barrysmith@barrysmith-57.mcs.anl.gov|ChangeSet|20050531182816|58698 ChangeSet   1.1353 05/05/31 13:28:16 barrysmith@barrysmith-57.mcs.anl.gov +1 -0   Not sure why you used sets.Set() cause breaks with python 2.4.1 so removed it   [barrysmith-57:~/petsc-dev] barrysmi% python   Python 2.4.1 (#2, Mar 31 2005, 00:05:10)   [GCC 3.3 20030304 (Apple Computer, Inc. build 1666)] on darwin   >>> import sets   >>>  inc = sets.Set(['foo'])     File "<stdin>", line 1       inc = sets.Set(['foo'])       ^   SyntaxError: invalid syntax   >>> inc = sets.Set(['foo'])   >>> print inc   Set(['foo'])   >>> print inc[0]   Traceback (most recent call last):   TypeError: unindexable object   >>>
  config/python.py
    1.11 05/05/31 13:22:45 barrysmith@barrysmith-57.mcs.anl.gov +1 -1
    Not sure why you used sets.Set() cause breaks with python 2.4.1 so removed it
    [barrysmith-57:~/petsc-dev] barrysmi% python
    Python 2.4.1 (#2, Mar 31 2005, 00:05:10) 
    [GCC 3.3 20030304 (Apple Computer, Inc. build 1666)] on darwin
    >>> import sets
    >>>  inc = sets.Set(['foo'])
      File "<stdin>", line 1
        inc = sets.Set(['foo'])
        ^
    SyntaxError: invalid syntax
    >>> inc = sets.Set(['foo'])
    >>> print inc
    Set(['foo'])
    >>> print inc[0]
    Traceback (most recent call last):
    TypeError: unindexable object
    >>>